services:
  taskpal:
    image: ghcr.io/blakdav/taskpal.md:latest
    container_name: taskpal
    restart: unless-stopped
    ports:
      - "8092:8080"
    volumes:
      - volumemap:/data
    env_file:
      - .env
